import Header from "@/components/Header";
import AddSlot from "@/components/AddSlot";
import Footer from "@/components/Footer";

// ✅ SEO Metadata
export const metadata = {
  title: "Disclaimer | SIP Calculator",
  description:
    "Read the Disclaimer for SIP Calculator. Learn about the limitations of estimated returns, financial assumptions, and the educational purpose of our SIP tools.",
};

export default function DisclaimerPage() {
  return (
    <main className="bg-gray-50 dark:bg-gray-950 min-h-screen text-gray-800 dark:text-gray-100">
      {/* Header */}
      <Header />

      {/* Hero Section */}
      <section className="relative isolate overflow-hidden pt-32 pb-16 text-center">
        <div className="absolute inset-0 -z-10 bg-gradient-to-b from-emerald-100 via-blue-50 to-transparent dark:from-gray-900 dark:via-gray-800 dark:to-gray-900" />
        <div className="max-w-3xl mx-auto px-6">
          <h1 className="text-4xl sm:text-5xl font-extrabold text-gray-900 dark:text-white mb-4">
            Disclaimer
          </h1>
          <p className="text-lg sm:text-xl text-gray-600 dark:text-gray-300 leading-relaxed">
            Please read this disclaimer carefully before using{" "}
            <strong>SIP Calculator</strong>. The information provided on our
            website is intended for general educational and informational
            purposes only.
          </p>
        </div>
      </section>

      {/* Main Content */}
      <div className="max-w-5xl mx-auto px-6 py-2 space-y-4">
        <AddSlot />

        {/* 1. General Information */}
        <section>
          <h2 className="text-2xl font-bold mb-3 text-emerald-600">
            1. General Information
          </h2>
          <p className="text-lg leading-relaxed text-gray-700 dark:text-gray-300">
            The information, data, and figures generated by{" "}
            <strong>SIP Calculator</strong> are intended to help users understand
            potential investment growth under different scenarios. While every
            effort is made to ensure accuracy, the results shown are purely
            indicative and based on assumptions of expected returns, tenure, and
            investment amount.
          </p>
          <AddSlot />
        </section>

        {/* 2. Not Financial Advice */}
        <section>
          <h2 className="text-2xl font-bold mb-3 text-emerald-600">
            2. Not Financial Advice
          </h2>
          <p className="text-lg leading-relaxed text-gray-700 dark:text-gray-300">
            The information on this website does not constitute financial,
            investment, tax, or legal advice. Users are encouraged to consult
            with a certified financial advisor or investment professional before
            making any investment decisions. <strong>SIP Calculator</strong> is
            a self-help tool designed for educational purposes only.
          </p>
          <AddSlot />
        </section>

        {/* 3. Accuracy and Reliability */}
        <section>
          <h2 className="text-2xl font-bold mb-3 text-emerald-600">
            3. Accuracy and Reliability
          </h2>
          <p className="text-lg leading-relaxed text-gray-700 dark:text-gray-300">
            Although we strive to maintain the highest levels of accuracy,{" "}
            <strong>SIP Calculator</strong> does not guarantee that the
            information or estimated results are complete, up to date, or free
            from error. Market conditions, fund performance, inflation, and
            other factors can significantly impact actual investment outcomes.
          </p>
          <AddSlot />
        </section>

        {/* 4. Limitation of Liability */}
        <section>
          <h2 className="text-2xl font-bold mb-3 text-emerald-600">
            4. Limitation of Liability
          </h2>
          <p className="text-lg leading-relaxed text-gray-700 dark:text-gray-300">
            Under no circumstances shall <strong>SIP Calculator</strong>, its
            owners, developers, or affiliates be held liable for any direct,
            indirect, incidental, or consequential damages resulting from the
            use or misuse of this website or reliance upon the results provided.
            Users accept full responsibility for all decisions made based on
            their interpretation of the calculator’s results.
          </p>
          <AddSlot />
        </section>

        {/* 5. External Links */}
        <section>
          <h2 className="text-2xl font-bold mb-3 text-emerald-600">
            5. External Links
          </h2>
          <p className="text-lg leading-relaxed text-gray-700 dark:text-gray-300">
            Our website may contain links to third-party websites or investment
            tools for additional information. These links are provided for your
            convenience only. <strong>SIP Calculator</strong> does not endorse
            or guarantee the content, reliability, or privacy policies of any
            external websites.
          </p>
          <AddSlot />
        </section>

        {/* 6. User Responsibility */}
        <section>
          <h2 className="text-2xl font-bold mb-3 text-emerald-600">
            6. User Responsibility
          </h2>
          <p className="text-lg leading-relaxed text-gray-700 dark:text-gray-300">
            By using <strong>SIP Calculator</strong>, you acknowledge that all
            investment decisions you make are your sole responsibility. You
            agree not to hold the platform or its team accountable for any
            financial losses or misinterpretations arising from your use of our
            tools or resources.
          </p>
          <AddSlot />
        </section>

        {/* 7. Updates to This Disclaimer */}
        <section>
          <h2 className="text-2xl font-bold mb-3 text-emerald-600">
            7. Updates to This Disclaimer
          </h2>
          <p className="text-lg leading-relaxed text-gray-700 dark:text-gray-300">
            We may revise or update this disclaimer from time to time to reflect
            changes in our operations, laws, or policies. Any modifications will
            take effect immediately upon posting. You are encouraged to review
            this page periodically to stay informed about any changes.
          </p>
          <AddSlot />
        </section>

        {/* 8. Contact Information */}
        <section>
          <h2 className="text-2xl font-bold mb-3 text-emerald-600">
            8. Contact Information
          </h2>
          <p className="text-lg leading-relaxed text-gray-700 dark:text-gray-300">
            If you have questions or concerns regarding this Disclaimer, please
            reach out through our{" "}
            <a
              href="/contact"
              className="text-blue-600 dark:text-blue-400 hover:underline"
            >
              Contact Page
            </a>
            . We value transparency and will do our best to address your
            inquiries promptly.
          </p>
        </section>

        <AddSlot />
      </div>

      {/* Footer */}
      <Footer />
    </main>
  );
}
